- name: prepare locale
  become: true
  tags:
    - ros
    - ros-prepare
  shell:
    cmd: "locale-gen en_US en_US.UTF-8; update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8"
  when: ansible_facts['os_family'] == "Debian"
