apt_packages:
  - exa
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  # - zsh-history-substring-search
  - bat
  - python3-pip
  - python3-pipdeptree
  - git
  - tmux
  - htop
  - sudo
  - neovim
  - vim
  - emacs
  - neofetch
  - ripgrep
  - zoxide
  - build-essential
  - python3-ipython
  - rsync
  - curl
  - mosh
